plugins:
  - name: protoc-gen-go
    implementation: golang:protobuf:protoc-gen-go
    deps:
      - "@org_golang_google_protobuf//reflect/protoreflect"
      - "@org_golang_google_protobuf//runtime/protoimpl"
  - name: protoc-gen-go-grpc
    implementation: grpc:grpc-go:protoc-gen-go-grpc
    deps:
      - "@org_golang_google_grpc//:go_default_library"
      - "@org_golang_google_grpc//codes"
      - "@org_golang_google_grpc//status"
  - name: closure_js
    implementation: builtin:js:closure
  - name: protoc-gen-grpc-js
    implementation: stackb:grpc.js:protoc-gen-grpc-js
rules:
  - name: proto_compile
    implementation: stackb:rules_proto:proto_compile
    visibility:
      -  //visibility:public
  - name: proto_descriptor_set
    implementation: stackb:rules_proto:proto_descriptor_set
    visibility:
      -  //visibility:public
  - name: proto_go_library
    enabled: true
    implementation: stackb:rules_proto:proto_go_library
    visibility:
      -  //visibility:public
    resolves:
      - "google/protobuf/([a-z]+).proto @org_golang_google_protobuf//types/known/${1}pb"
      - "google/protobuf/(field_mask).proto @org_golang_google_protobuf//types/known/fieldmaskpb"
      - "google/protobuf/(descriptor|plugin).proto @org_golang_google_protobuf//types/${1}pb"
  - name: proto_closure_js_library
    implementation: stackb:rules_proto:proto_closure_js_library
    visibility:
      -  //visibility:public
  - name: grpc_closure_js_library
    implementation: stackb:rules_proto:grpc_closure_js_library
    visibility:
      -  //visibility:public
languages:
  - name: descriptor
    plugins:
      - protoc-gen-go
    rules:
      - proto_descriptor_set
    enabled: false
  - name: go
    plugins:
      - protoc-gen-go
      - protoc-gen-go-grpc
    rules:
      - proto_compile
      - proto_go_library
    enabled: false
